python run_seq_labeling.py  --data_dir data ^
                            --model_type layoutlm ^
                            --model_name_or_path mymodel/ ^
                            --do_lower_case ^
                            --max_seq_length 512 ^
                            --do_predict ^
                            --num_train_epochs 10.0 ^
                            --logging_steps 10 ^
                            --save_steps 250 ^
                            --output_dir output ^
                            --labels data/labels.txt ^
                            --per_gpu_train_batch_size 4